# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0003_auto_20161104_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='entity_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
